/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package CasosDeUsos;

import CasoUsoAdmin.JIFActualizarParametro;
import CasoUsoAdmin.JIFActualizarUsuario;
import CasoUsoAdmin.JIFConsultarParametro;
import CasoUsoAdmin.JIFConsultarUsuario;
import CasoUsoAdmin.JIFEliminarUsuario;
import CasoUsoAdmin.JIFRegistrarParametro;
import CasoUsoAdmin.JIFRegistrarUsuario;
import javax.swing.JInternalFrame;

/**
 *
 * @author HP
 */
public class JIFcasosUsoAdministracion extends javax.swing.JInternalFrame {

    JIFRegistrarUsuario jifRegistrarUsuario;
    JIFRegistrarParametro jifRegistrarPara;
    JIFActualizarUsuario jifActualizarU;
    JIFConsultarUsuario jifConsultarU;
    JIFEliminarUsuario jifEliminarU;
    JIFActualizarParametro jifActualizarP;
    JIFConsultarParametro jifConsultarP;
    
    
    public JIFcasosUsoAdministracion() {
        initComponents();
    }
    
     public void centrarVentanaI(JInternalFrame jfcentrar){
        int x1 = (jDeskAdmin.getWidth()/2)- jfcentrar.getWidth()/2;
        int y1 = (jDeskAdmin.getHeight()/2)- jfcentrar.getHeight()/2;
        if(jfcentrar.isShowing()){
            jfcentrar.setLocation(x1, y1);
        }else{
            jDeskAdmin.add(jfcentrar);
            jfcentrar.setLocation(x1, y1);
            jfcentrar.show();
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jDeskAdmin = new javax.swing.JDesktopPane();
        jLabel7 = new javax.swing.JLabel();
        jBRegistrarUsuarios = new javax.swing.JButton();
        jBRegistrarParametro = new javax.swing.JButton();
        jBActualizarUsuario = new javax.swing.JButton();
        jBConsultarUsuario = new javax.swing.JButton();
        jBEliminarUsuario = new javax.swing.JButton();
        jBConsultarPara = new javax.swing.JButton();
        jBActualizarP = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jDeskAdmin.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(128, 128, 131));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img1/home.png"))); // NOI18N
        jLabel7.setText("ADMINISTRACIÓN");

        jBRegistrarUsuarios.setText("REGISTRAR USUARIO");
        jBRegistrarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRegistrarUsuariosActionPerformed(evt);
            }
        });

        jBRegistrarParametro.setText("REGISTRAR PARÁMETRO");
        jBRegistrarParametro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRegistrarParametroActionPerformed(evt);
            }
        });

        jBActualizarUsuario.setText("ACTUALIZAR USUARIO");
        jBActualizarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBActualizarUsuarioActionPerformed(evt);
            }
        });

        jBConsultarUsuario.setText("CONSULTAR USUARIO");
        jBConsultarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConsultarUsuarioActionPerformed(evt);
            }
        });

        jBEliminarUsuario.setText("ELIMINAR USUARIO");
        jBEliminarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEliminarUsuarioActionPerformed(evt);
            }
        });

        jBConsultarPara.setText("COSULTAR PARÁMETRO");
        jBConsultarPara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConsultarParaActionPerformed(evt);
            }
        });

        jBActualizarP.setText("ACTUALIZAR PARÁMETRO");
        jBActualizarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBActualizarPActionPerformed(evt);
            }
        });

        jDeskAdmin.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDeskAdmin.setLayer(jBRegistrarUsuarios, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDeskAdmin.setLayer(jBRegistrarParametro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDeskAdmin.setLayer(jBActualizarUsuario, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDeskAdmin.setLayer(jBConsultarUsuario, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDeskAdmin.setLayer(jBEliminarUsuario, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDeskAdmin.setLayer(jBConsultarPara, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDeskAdmin.setLayer(jBActualizarP, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDeskAdminLayout = new javax.swing.GroupLayout(jDeskAdmin);
        jDeskAdmin.setLayout(jDeskAdminLayout);
        jDeskAdminLayout.setHorizontalGroup(
            jDeskAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDeskAdminLayout.createSequentialGroup()
                .addGroup(jDeskAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDeskAdminLayout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(jLabel7))
                    .addGroup(jDeskAdminLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jBRegistrarUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jBActualizarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jBConsultarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jBEliminarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDeskAdminLayout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jBRegistrarParametro, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(jBActualizarP)
                        .addGap(46, 46, 46)
                        .addComponent(jBConsultarPara, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(129, Short.MAX_VALUE))
        );
        jDeskAdminLayout.setVerticalGroup(
            jDeskAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDeskAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jDeskAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBRegistrarUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBActualizarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBConsultarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBEliminarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(jDeskAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBRegistrarParametro, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBActualizarP, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBConsultarPara, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(246, Short.MAX_VALUE))
        );

        jPanel1.add(jDeskAdmin, new java.awt.GridBagConstraints());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 943, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBRegistrarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRegistrarUsuariosActionPerformed
        if(!(jifRegistrarUsuario instanceof JIFRegistrarUsuario)){
            jifRegistrarUsuario = new JIFRegistrarUsuario();
        }
        centrarVentanaI(jifRegistrarUsuario);
    }//GEN-LAST:event_jBRegistrarUsuariosActionPerformed

    private void jBRegistrarParametroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRegistrarParametroActionPerformed
         if(!(jifRegistrarPara instanceof JIFRegistrarParametro)){
            jifRegistrarPara = new JIFRegistrarParametro();
        }
        centrarVentanaI(jifRegistrarPara);
    }//GEN-LAST:event_jBRegistrarParametroActionPerformed

    private void jBActualizarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBActualizarUsuarioActionPerformed
        if(!(jifActualizarU instanceof JIFActualizarUsuario)){
            jifActualizarU = new JIFActualizarUsuario();
        }
        centrarVentanaI(jifActualizarU);
    }//GEN-LAST:event_jBActualizarUsuarioActionPerformed

    private void jBConsultarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConsultarUsuarioActionPerformed
         if(!(jifConsultarU instanceof JIFConsultarUsuario)){
            jifConsultarU = new JIFConsultarUsuario();
        }
        centrarVentanaI(jifConsultarU);
    }//GEN-LAST:event_jBConsultarUsuarioActionPerformed

    private void jBEliminarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEliminarUsuarioActionPerformed
         if(!(jifEliminarU instanceof JIFEliminarUsuario)){
            jifEliminarU = new JIFEliminarUsuario();
        }
        centrarVentanaI(jifEliminarU);
    }//GEN-LAST:event_jBEliminarUsuarioActionPerformed

    private void jBConsultarParaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConsultarParaActionPerformed
         if(!(jifConsultarP instanceof JIFConsultarParametro)){
            jifConsultarP = new JIFConsultarParametro();
        }
        centrarVentanaI(jifConsultarP);
    }//GEN-LAST:event_jBConsultarParaActionPerformed

    private void jBActualizarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBActualizarPActionPerformed
         if(!(jifActualizarP instanceof JIFActualizarParametro)){
            jifActualizarP = new JIFActualizarParametro();
        }
        centrarVentanaI(jifActualizarP);
    }//GEN-LAST:event_jBActualizarPActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBActualizarP;
    private javax.swing.JButton jBActualizarUsuario;
    private javax.swing.JButton jBConsultarPara;
    private javax.swing.JButton jBConsultarUsuario;
    private javax.swing.JButton jBEliminarUsuario;
    private javax.swing.JButton jBRegistrarParametro;
    private javax.swing.JButton jBRegistrarUsuarios;
    private javax.swing.JDesktopPane jDeskAdmin;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
