/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package CasosDeUsos;

import CasoUsoPersonal.JIFActualizarPersonal;
import CasoUsoPersonal.JIFConsultarPersonal;
import CasoUsoPersonal.JIFEliminarPersonal;
import CasoUsoPersonal.JIFRegistrarPersonal;
import javax.swing.JInternalFrame;

/**
 *
 * @author HP
 */
public class JIFcasosUsoPersonal extends javax.swing.JInternalFrame {

    JIFActualizarPersonal jifActualizarPer;
    JIFRegistrarPersonal jifResgisPer;
    JIFConsultarPersonal jifConsultarP;
    JIFEliminarPersonal jifEliminarP;
    
    public JIFcasosUsoPersonal() {
        initComponents();
    }
    
     public void centrarVentanaI(JInternalFrame jfcentrar){
        int x1 = (jDeskPersonal.getWidth()/2)- jfcentrar.getWidth()/2;
        int y1 = (jDeskPersonal.getHeight()/2)- jfcentrar.getHeight()/2;
        if(jfcentrar.isShowing()){
            jfcentrar.setLocation(x1, y1);
        }else{
            jDeskPersonal.add(jfcentrar);
            jfcentrar.setLocation(x1, y1);
            jfcentrar.show();
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jDeskPersonal = new javax.swing.JDesktopPane();
        jLabel7 = new javax.swing.JLabel();
        jBRegistrarPersonal = new javax.swing.JButton();
        jBActualizarPersonal = new javax.swing.JButton();
        jBListaPersonal = new javax.swing.JButton();
        jBInfoSocios = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jDeskPersonal.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(128, 128, 131));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img1/home.png"))); // NOI18N
        jLabel7.setText("PERSONAL");

        jBRegistrarPersonal.setText("REGISTRAR");
        jBRegistrarPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRegistrarPersonalActionPerformed(evt);
            }
        });

        jBActualizarPersonal.setText("ACTUALIZAR");
        jBActualizarPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBActualizarPersonalActionPerformed(evt);
            }
        });

        jBListaPersonal.setText("CONSULTAR");
        jBListaPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBListaPersonalActionPerformed(evt);
            }
        });

        jBInfoSocios.setText("ELIMINAR");
        jBInfoSocios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBInfoSociosActionPerformed(evt);
            }
        });

        jDeskPersonal.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDeskPersonal.setLayer(jBRegistrarPersonal, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDeskPersonal.setLayer(jBActualizarPersonal, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDeskPersonal.setLayer(jBListaPersonal, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDeskPersonal.setLayer(jBInfoSocios, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDeskPersonalLayout = new javax.swing.GroupLayout(jDeskPersonal);
        jDeskPersonal.setLayout(jDeskPersonalLayout);
        jDeskPersonalLayout.setHorizontalGroup(
            jDeskPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDeskPersonalLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jBRegistrarPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(jBActualizarPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jBListaPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(jBInfoSocios, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
            .addGroup(jDeskPersonalLayout.createSequentialGroup()
                .addGap(213, 213, 213)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDeskPersonalLayout.setVerticalGroup(
            jDeskPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDeskPersonalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jDeskPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBRegistrarPersonal, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(jBActualizarPersonal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBListaPersonal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBInfoSocios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(341, Short.MAX_VALUE))
        );

        jPanel1.add(jDeskPersonal, new java.awt.GridBagConstraints());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 943, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBRegistrarPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRegistrarPersonalActionPerformed
        if(!(jifResgisPer instanceof JIFRegistrarPersonal)){
            jifResgisPer = new JIFRegistrarPersonal();
        }
        centrarVentanaI(jifResgisPer);

    }//GEN-LAST:event_jBRegistrarPersonalActionPerformed

    private void jBActualizarPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBActualizarPersonalActionPerformed
        if(!(jifActualizarPer instanceof JIFActualizarPersonal)){
            jifActualizarPer = new JIFActualizarPersonal();
        }
        centrarVentanaI(jifActualizarPer);
    }//GEN-LAST:event_jBActualizarPersonalActionPerformed

    private void jBListaPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBListaPersonalActionPerformed
        if(!(jifConsultarP instanceof JIFConsultarPersonal)){
            jifConsultarP = new JIFConsultarPersonal();
        }
        centrarVentanaI(jifConsultarP);
    }//GEN-LAST:event_jBListaPersonalActionPerformed

    private void jBInfoSociosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBInfoSociosActionPerformed
        if(!(jifEliminarP instanceof JIFEliminarPersonal)){
            jifEliminarP = new JIFEliminarPersonal();
        }
        centrarVentanaI(jifEliminarP);
    }//GEN-LAST:event_jBInfoSociosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBActualizarPersonal;
    private javax.swing.JButton jBInfoSocios;
    private javax.swing.JButton jBListaPersonal;
    private javax.swing.JButton jBRegistrarPersonal;
    private javax.swing.JDesktopPane jDeskPersonal;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
