
package CasosDeUsos;

import CasoUsoInventario.JIFActualizarArt;
import CasoUsoInventario.JIFConsultarInvHabi;
import CasoUsoInventario.JIFRegistrarArt;
import javax.swing.JInternalFrame;


/**
 *
 * @author Brandon Oña
 */
public class JIFcasosUsoInventario extends javax.swing.JInternalFrame {

    JIFActualizarArt jifActualizarArt;
    JIFConsultarInvHabi jifConsultarInvHabi;
    JIFRegistrarArt jifInventario;
    
            
    public JIFcasosUsoInventario() {
        initComponents();
    }
    
     public void centrarVentana(JInternalFrame jfcentrar){
        int x1 = (jDeskInventario.getWidth()/2)- jfcentrar.getWidth()/2;
        int y1 = (jDeskInventario.getHeight()/2)- jfcentrar.getHeight()/2;
        if(jfcentrar.isShowing()){
            jfcentrar.setLocation(x1, y1);
        }else{
            jDeskInventario.add(jfcentrar);
            jfcentrar.setLocation(x1, y1);
            jfcentrar.show();
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jDeskInventario = new javax.swing.JDesktopPane();
        jLabel7 = new javax.swing.JLabel();
        jBRegistrarInven = new javax.swing.JButton();
        jBInventarioG = new javax.swing.JButton();
        jBInventarioHabi = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jDeskInventario.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(128, 128, 131));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img1/home.png"))); // NOI18N
        jLabel7.setText("INVENTARIO");

        jBRegistrarInven.setText("REGISTRAR ARTÍCULO");
        jBRegistrarInven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRegistrarInvenActionPerformed(evt);
            }
        });

        jBInventarioG.setText("ACTUALIZAR ARTÍCULO");
        jBInventarioG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBInventarioGActionPerformed(evt);
            }
        });

        jBInventarioHabi.setText("CONSULTAR INVENTARIO");
        jBInventarioHabi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBInventarioHabiActionPerformed(evt);
            }
        });

        jDeskInventario.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDeskInventario.setLayer(jBRegistrarInven, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDeskInventario.setLayer(jBInventarioG, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDeskInventario.setLayer(jBInventarioHabi, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDeskInventarioLayout = new javax.swing.GroupLayout(jDeskInventario);
        jDeskInventario.setLayout(jDeskInventarioLayout);
        jDeskInventarioLayout.setHorizontalGroup(
            jDeskInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDeskInventarioLayout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jBRegistrarInven, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addComponent(jBInventarioG)
                .addGap(118, 118, 118)
                .addComponent(jBInventarioHabi)
                .addGap(106, 106, 106))
            .addGroup(jDeskInventarioLayout.createSequentialGroup()
                .addGap(252, 252, 252)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDeskInventarioLayout.setVerticalGroup(
            jDeskInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDeskInventarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jDeskInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBInventarioHabi, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jDeskInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBRegistrarInven, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBInventarioG, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(341, Short.MAX_VALUE))
        );

        jPanel1.add(jDeskInventario, new java.awt.GridBagConstraints());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 943, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBRegistrarInvenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRegistrarInvenActionPerformed
        if(!(jifInventario instanceof JIFRegistrarArt)){
            jifInventario = new JIFRegistrarArt();
        }
        centrarVentana(jifInventario);
    }//GEN-LAST:event_jBRegistrarInvenActionPerformed

    private void jBInventarioGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBInventarioGActionPerformed
       if(!(jifActualizarArt instanceof JIFActualizarArt)){
            jifActualizarArt = new JIFActualizarArt();
        }
        centrarVentana(jifActualizarArt);
    }//GEN-LAST:event_jBInventarioGActionPerformed

    private void jBInventarioHabiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBInventarioHabiActionPerformed
        if(!(jifConsultarInvHabi instanceof JIFConsultarInvHabi)){
            jifConsultarInvHabi = new JIFConsultarInvHabi();
        }
        centrarVentana(jifConsultarInvHabi);
    }//GEN-LAST:event_jBInventarioHabiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBInventarioG;
    private javax.swing.JButton jBInventarioHabi;
    private javax.swing.JButton jBRegistrarInven;
    private javax.swing.JDesktopPane jDeskInventario;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    private static class JIFRegistrarInventario {

        public JIFRegistrarInventario() {
        }
    }
}
