/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package CasosDeUsos;

import CasosUsoEgresos.JIFConsultarPago;
import CasosUsoEgresos.JIFRegistroPagoSalario;
import CasosUsoEgresos.JIFRegistroPagoServicios;
import javax.swing.JInternalFrame;

/**
 *
 * @author Brandon Oña
 */
public class JIFcasosUsoEgresos extends javax.swing.JInternalFrame {

    JIFRegistroPagoSalario jifRregistarSalario;
    JIFConsultarPago jifConsultarPago;
    JIFRegistroPagoServicios jifPagoServicios;

    public JIFcasosUsoEgresos() {
        initComponents();
    }
    
     public void centrarVentanaI(JInternalFrame jfcentrar){
        int x1 = (jDeskEgresos.getWidth()/2)- jfcentrar.getWidth()/2;
        int y1 = (jDeskEgresos.getHeight()/2)- jfcentrar.getHeight()/2;
        if(jfcentrar.isShowing()){
            jfcentrar.setLocation(x1, y1);
        }else{
            jDeskEgresos.add(jfcentrar);
            jfcentrar.setLocation(x1, y1);
            jfcentrar.show();
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jDeskEgresos = new javax.swing.JDesktopPane();
        jLabel7 = new javax.swing.JLabel();
        jBSaldoPersonal = new javax.swing.JButton();
        jBGastoGeneral = new javax.swing.JButton();
        jBServiciosBasico = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jDeskEgresos.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(128, 128, 131));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img1/home.png"))); // NOI18N
        jLabel7.setText("EGRESOS");

        jBSaldoPersonal.setText("REGISTRAR PAGO SALARIOS");
        jBSaldoPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSaldoPersonalActionPerformed(evt);
            }
        });

        jBGastoGeneral.setText("CONSULTAR PAGOS");
        jBGastoGeneral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGastoGeneralActionPerformed(evt);
            }
        });

        jBServiciosBasico.setText("REGISTRAR PAGO SERVICIOS");
        jBServiciosBasico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBServiciosBasicoActionPerformed(evt);
            }
        });

        jDeskEgresos.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDeskEgresos.setLayer(jBSaldoPersonal, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDeskEgresos.setLayer(jBGastoGeneral, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDeskEgresos.setLayer(jBServiciosBasico, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDeskEgresosLayout = new javax.swing.GroupLayout(jDeskEgresos);
        jDeskEgresos.setLayout(jDeskEgresosLayout);
        jDeskEgresosLayout.setHorizontalGroup(
            jDeskEgresosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDeskEgresosLayout.createSequentialGroup()
                .addGroup(jDeskEgresosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDeskEgresosLayout.createSequentialGroup()
                        .addGap(292, 292, 292)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDeskEgresosLayout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jBSaldoPersonal)
                        .addGap(91, 91, 91)
                        .addComponent(jBServiciosBasico)
                        .addGap(87, 87, 87)
                        .addComponent(jBGastoGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(159, Short.MAX_VALUE))
        );
        jDeskEgresosLayout.setVerticalGroup(
            jDeskEgresosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDeskEgresosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jDeskEgresosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(jBServiciosBasico, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBSaldoPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBGastoGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(351, Short.MAX_VALUE))
        );

        jPanel1.add(jDeskEgresos, new java.awt.GridBagConstraints());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 943, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBSaldoPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSaldoPersonalActionPerformed
        if(!(jifRregistarSalario instanceof JIFRegistroPagoSalario)){
            jifRregistarSalario = new JIFRegistroPagoSalario();
        }
        centrarVentanaI(jifRregistarSalario);

    }//GEN-LAST:event_jBSaldoPersonalActionPerformed

    private void jBServiciosBasicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBServiciosBasicoActionPerformed
        if(!(jifPagoServicios instanceof JIFRegistroPagoServicios)){
            jifPagoServicios = new JIFRegistroPagoServicios();
        }
        centrarVentanaI(jifPagoServicios);
    }//GEN-LAST:event_jBServiciosBasicoActionPerformed

    private void jBGastoGeneralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGastoGeneralActionPerformed
        if(!(jifConsultarPago instanceof JIFConsultarPago)){
            jifConsultarPago = new JIFConsultarPago();
        }
        centrarVentanaI(jifConsultarPago);
    }//GEN-LAST:event_jBGastoGeneralActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBGastoGeneral;
    private javax.swing.JButton jBSaldoPersonal;
    private javax.swing.JButton jBServiciosBasico;
    private javax.swing.JDesktopPane jDeskEgresos;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
