/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package CasosDeUsos;

import CasosUsoIngresos.JIFConsultarCobro;
import CasosUsoIngresos.JIFRegistrarCobro;
import CasosUsoIngresos.JIFNotaVenta;
import javax.swing.JInternalFrame;

/**
 *
 * @author HP
 */
public class JIFcasosUsoIngreso extends javax.swing.JInternalFrame {
    
    JIFRegistrarCobro jifRegistrarCobro;
    JIFConsultarCobro jifConusltarC;
    JIFNotaVenta jiFactura;
    
    public JIFcasosUsoIngreso() {
        initComponents();
    }
    
     public void centrarVentanaI(JInternalFrame jfcentrar){
        int x1 = (jDeskIngresos.getWidth()/2)- jfcentrar.getWidth()/2;
        int y1 = (jDeskIngresos.getHeight()/2)- jfcentrar.getHeight()/2;
        if(jfcentrar.isShowing()){
            jfcentrar.setLocation(x1, y1);
        }else{
            jDeskIngresos.add(jfcentrar);
            jfcentrar.setLocation(x1, y1);
            jfcentrar.show();
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jDeskIngresos = new javax.swing.JDesktopPane();
        jLabel7 = new javax.swing.JLabel();
        jBInformeFecha = new javax.swing.JButton();
        jBInformeDiario = new javax.swing.JButton();
        jBFactura = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jDeskIngresos.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(128, 128, 131));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img1/home.png"))); // NOI18N
        jLabel7.setText("INGRESOS");

        jBInformeFecha.setText("CONSULTAR COBRO");
        jBInformeFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBInformeFechaActionPerformed(evt);
            }
        });

        jBInformeDiario.setText("REGISTRAR COBRO");
        jBInformeDiario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBInformeDiarioActionPerformed(evt);
            }
        });

        jBFactura.setText("NOTA DE VENTA");
        jBFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBFacturaActionPerformed(evt);
            }
        });

        jDeskIngresos.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDeskIngresos.setLayer(jBInformeFecha, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDeskIngresos.setLayer(jBInformeDiario, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDeskIngresos.setLayer(jBFactura, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDeskIngresosLayout = new javax.swing.GroupLayout(jDeskIngresos);
        jDeskIngresos.setLayout(jDeskIngresosLayout);
        jDeskIngresosLayout.setHorizontalGroup(
            jDeskIngresosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDeskIngresosLayout.createSequentialGroup()
                .addContainerGap(162, Short.MAX_VALUE)
                .addComponent(jBInformeDiario, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jBInformeFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jBFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(220, 220, 220))
            .addGroup(jDeskIngresosLayout.createSequentialGroup()
                .addGap(340, 340, 340)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDeskIngresosLayout.setVerticalGroup(
            jDeskIngresosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDeskIngresosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jDeskIngresosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBInformeFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBInformeDiario, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(343, Short.MAX_VALUE))
        );

        jPanel1.add(jDeskIngresos, new java.awt.GridBagConstraints());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 507, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBInformeFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBInformeFechaActionPerformed
        if(!(jifConusltarC instanceof JIFConsultarCobro)){
            jifConusltarC = new JIFConsultarCobro();
        }
        centrarVentanaI(jifConusltarC);

    }//GEN-LAST:event_jBInformeFechaActionPerformed

    private void jBInformeDiarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBInformeDiarioActionPerformed
        if(!(jifRegistrarCobro instanceof JIFRegistrarCobro)){
            jifRegistrarCobro = new JIFRegistrarCobro();
        }
        centrarVentanaI(jifRegistrarCobro);
    }//GEN-LAST:event_jBInformeDiarioActionPerformed

    private void jBFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBFacturaActionPerformed
        if(!(jiFactura instanceof JIFNotaVenta)){
            jiFactura = new JIFNotaVenta();
        }
        centrarVentanaI(jiFactura);
    }//GEN-LAST:event_jBFacturaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBFactura;
    private javax.swing.JButton jBInformeDiario;
    private javax.swing.JButton jBInformeFecha;
    private javax.swing.JDesktopPane jDeskIngresos;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
