/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package CasoUsoHuesped;


import Negocio.Conexion;
import Negocio.Huesped;
import Negocio.Metodos;
import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import static java.lang.Integer.parseInt;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Brandon Oña
 */
public class JIFConsultarHuesped extends javax.swing.JInternalFrame {

    Conexion con = new Conexion();
    Metodos ins;

    public JIFConsultarHuesped() {
        initComponents();
        ins = new Metodos();
        MostrarTablaH("");
        //this.jBGuardarHExtranjero.setEnabled(false);
        //this.jBGuardarHNacional.setEnabled(false);
        //this.jTableHuesped.setEnabled(false);
    }

    public void MostrarTablaH(String Nombre) {
        DefaultTableModel Huesped = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column) {
                if (column == 6) {
                    return true;
                } else {
                    return false;
                }

            }

        };

        Huesped.addColumn("ID Huesped");
        Huesped.addColumn("Identificación");
        Huesped.addColumn("Nombre");
        Huesped.addColumn("Apellido");
        Huesped.addColumn("Teléfono");
        Huesped.addColumn("Correo");
        //Huesped.addColumn("Habitación");
        this.jTableHuesped.setModel(Huesped);
        String sql = "";

        if (Nombre.equals("")) {
            sql = "SELECT * FROM HUESPEDES";
        } else {
            sql = "SELECT * FROM HUESPEDES WHERE Identificación like '%" + Nombre + "%'";
        }
        String datos[] = new String[6];
        Statement st;
        try {
            st = con.getConexion().createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                datos[0] = rs.getString(2);
                datos[1] = rs.getString(3);
                datos[2] = rs.getString(4);
                datos[3] = rs.getString(5);
                datos[4] = rs.getString(6);
                datos[5] = rs.getString(7);
                //datos[5] = rs.getString(6);
                //datos[6] = rs.getString(7);
                Huesped.addRow(datos);
            }
            jTableHuesped.setModel(Huesped);

        } catch (SQLException ex) {
            Logger.getLogger(JIFConsultarHuesped.class
                    .getName()).log(Level.SEVERE, null, ex);
            //JOptionPane.showMessageDialog(null, ex.toString());
        }
    }

    public void MostrarTablaClientesFrecuentes() {
        DefaultTableModel Huesped = new DefaultTableModel();
        //Huesped.addColumn("id");
        Huesped.addColumn("Identificación");
        Huesped.addColumn("Nombre");
        Huesped.addColumn("Apellido");
        Huesped.addColumn("N° de Ingresos");
        //Huesped.addColumn("Teléfono");
        //Huesped.addColumn("Correo");
        //Huesped.addColumn("Habitación");
        this.jTableHuesped.setModel(Huesped);
        String sql = "";

        sql = "Select Identificación, Nombre, Apellido, Count(*) as Registros from HUESPEDES Group by Identificación, Nombre, Apellido Having Count(*)>1";
        String datos[] = new String[4];
        Statement st;
        try {
            st = con.getConexion().createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                datos[0] = rs.getString(1);
                datos[1] = rs.getString(2);
                datos[2] = rs.getString(3);
                datos[3] = rs.getString(4);
                Huesped.addRow(datos);
            }
            jTableHuesped.setModel(Huesped);

        } catch (SQLException ex) {
            Logger.getLogger(JIFConsultarHuesped.class
                    .getName()).log(Level.SEVERE, null, ex);
            //JOptionPane.showMessageDialog(null, ex.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTablaH = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableHuesped = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jTextBuscarCedula = new javax.swing.JTextField();
        jBclientesFrecuentes = new javax.swing.JButton();
        jBtodosHuespedes = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);

        jTableHuesped.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableHuesped);

        jLabel7.setText("Ingrese la identificación del huésped a buscar");

        jTextBuscarCedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextBuscarCedulaKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanelTablaHLayout = new javax.swing.GroupLayout(jPanelTablaH);
        jPanelTablaH.setLayout(jPanelTablaHLayout);
        jPanelTablaHLayout.setHorizontalGroup(
            jPanelTablaHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTablaHLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanelTablaHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelTablaHLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextBuscarCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanelTablaHLayout.setVerticalGroup(
            jPanelTablaHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTablaHLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanelTablaHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextBuscarCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jBclientesFrecuentes.setText("Huéspedes frecuentes");
        jBclientesFrecuentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBclientesFrecuentesActionPerformed(evt);
            }
        });

        jBtodosHuespedes.setText("Todos los huéspedes");
        jBtodosHuespedes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtodosHuespedesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(237, 237, 237)
                .addComponent(jBclientesFrecuentes)
                .addGap(63, 63, 63)
                .addComponent(jBtodosHuespedes)
                .addGap(0, 274, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelTablaH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanelTablaH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtodosHuespedes)
                    .addComponent(jBclientesFrecuentes))
                .addGap(0, 100, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextBuscarCedulaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextBuscarCedulaKeyReleased
        MostrarTablaH(this.jTextBuscarCedula.getText());
    }//GEN-LAST:event_jTextBuscarCedulaKeyReleased

    private void jBclientesFrecuentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBclientesFrecuentesActionPerformed
        MostrarTablaClientesFrecuentes();
    }//GEN-LAST:event_jBclientesFrecuentesActionPerformed

    private void jBtodosHuespedesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtodosHuespedesActionPerformed
        MostrarTablaH("");
    }//GEN-LAST:event_jBtodosHuespedesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBclientesFrecuentes;
    private javax.swing.JButton jBtodosHuespedes;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanelTablaH;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableHuesped;
    private javax.swing.JTextField jTextBuscarCedula;
    // End of variables declaration//GEN-END:variables
}
